Repository smartytushar/Hactoberfest-2022, pull requests merged in 2022-10, with the labels that each got.

#1 C++
  BuySellStock.cpp
  ClimbingStair.cpp
  characterReplacement.cpp
  checkInclusion.cpp
Labels: hactoberfest-accepted

#3 I want T-shirt
  App.js
  App.test.js
  Benefit.jsx
  Caraousal.css
  Caraousal.js
  Download.jsx
  benefit.css
  body.css
  body.jsx
  footer.css
  footer.js
  foottext.jsx
  header.css
  header.js
  index.css
Labels: hacktoberfest-accepted

#4 Hacktoberfest
  coinchange2.cpp
Labels: hacktoberfest-accepted

#6 I want T-shirt
  about.html
  blog.html
  contact.html
  course.html
Labels: hacktoberfest-accepted

#13 Add files via upload
  linearsearch.cpp
Labels: hacktoberfest-accepted

#12 Create FlattenBinaryTreeToLinkedList.cpp
  FlattenBinaryTreeToLinkedList.cpp
Labels: hactoberfest-accepted

#11 Create Serialize and De-serialize binary tree
  Serialize and De-serialize binary tree
Labels: hactoberfest-accepted, hacktoberfest-accepted

#9 Create Matrix addition.py
  Matrix addition.py
Labels: hacktoberfest-accepted

#8 Create Calender.py
  Calender.py
Labels: hacktoberfest-accepted

#7 TeamOf2.cpp
  TeamOf2.cpp
Labels: hacktoberfest-accepted

#15 added cup plate.md
  Tea Cup/cup.html
  Tea Cup/style.css
Labels: hacktoberfest-accepted

#14 JAVA code add
  BubbleSort.java
  InsertionSort.txt
  MergeSort.java
  QuickSort.java
  SelectionSort.java
Labels: hacktoberfest-accepted

#17 The_skyline_problem.cpp
  The_skyline_problem.cpp
Labels: hacktoberfest-accepted

#16 Create binarysearch.cpp
  binarysearch.cpp
Labels: hacktoberfest-accepted

#24 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hacktoberfest-accepted

#22 Rotting Oranges LeetCode Optimal Solution
  Rotting Oranges.cpp
Labels: hacktoberfest-accepted

#21 Added prime-or-not.cpp
  prime-or-not.cpp
Labels: hacktoberfest-accepted

#20 Adding Snake Game.md
  Snakegame.py
Labels: hacktoberfest-accepted

#19 Aggressive Cows Problem (Binary Search)
  aggressiveCows.cpp
Labels: hacktoberfest-accepted

#18 Create FlattenBinaryTreetoLinkedList.cpp
  FlattenBinaryTreetoLinkedList.cpp
Labels: hacktoberfest-accepted

#25 Hey
  BinarySearch.cpp
  firstBadVersion.cpp
  searchInsertPosition.cpp
Labels: good first issue

#30 Create pdf_reader.py
  pdf_reader.py
Labels: hacktoberfest-accepted

#28 created a Wave Array
  waveArray.cpp
Labels: hacktoberfest-accepted

#29 Find GCD in single line
  GCD in single line
Labels: hacktoberfest-accepted
